# Generated by Django 4.2.7 on 2023-11-22 10:13

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordDatabase', '0002_passworddatabase_db_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='passworddatabase',
            name='db_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from=models.CharField(max_length=50), unique=True),
        ),
    ]
