# Generated by Django 4.2.7 on 2023-11-21 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passwordDatabase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('password_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passwordDatabase.passworddatabase')),
            ],
        ),
    ]
