# Generated by Django 4.2.7 on 2023-11-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='password_db',
            field=models.CharField(max_length=100),
        ),
    ]
