# Generated by Django 4.2.7 on 2023-11-21 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passwordDatabase', '0001_initial'),
        ('passwords', '0002_alter_password_password_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='password_db',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passwordDatabase.passworddatabase'),
        ),
    ]
